### PR TITLE
Added option to disable sound

### PR DESCRIPTION
**Pull request by brmbrmcar**
This is actually complete, and works.

### CODE REVIEW

**Comment by crumblingstatue** [comment]
What does this have to offer over #57?

**Comment by brmbrmcar** [comment]
I tried it first, pretty much. There isn't any indentation issues....

**Comment by brmbrmcar** [comment]
We have had a massive conversation over it.

**Comment by crumblingstatue** [comment]
> I tried it first, pretty much.

That's not a valid reason.

> There isn't any indentation issues....

There aren't any in #57 either, since a commit was added to fix them.

Your pull request does, however, add 2 unnecessary empty lines.

**Comment by brmbrmcar** [comment]
Well, I know this looks messy...

**Comment by crumblingstatue** [comment]
Alright, if you don't have any more reasons, I'll close this in favor of #57. Thanks for your time!

**Pull request closed without merging**
