### PR TITLE
Numeric ID Location fields

### PR DESCRIPTION
**Pull request by vinceh121**
A lot of resources about Undertale, like the fandom wiki, reference rooms by their IDs, which makes finding the exact map referenced rather complicated with only names selectable.
This PR implements a numeric field next to location inputs that allows users to directly input the location ID they want.

### CODE REVIEW

**Comment by KockaAdmiralac** [comment]
It looks like when an ID field is changed, the allowed location fields sync between themselves and both set the selected location to `null`. I'm not sure if this behavior was intentional in the first place (@Jacky720?) but it makes the feature this PR introduces pretty annoying (you change the INI location ID, the SAVE location resets to `null`, then you try to change the SAVE location ID and the INI location ID resets to `null`). Can you add a check for whether the allowed locations changed at all, and if they haven't don't update the values of selected locations?

**Comment by Jacky720** [comment]
It's not intentional. The check on line 903 of main.js was dependent on `null == undefined` until we upgraded everything to `===`. Kocka can fix the function calls with `null`s to use `undefined` a lot easier than I can.

**Comment by KockaAdmiralac** [comment]
Or you can just apply the diff in this PR (instead of doing what I mentioned previously):
```diff
diff --git a/main.js b/main.js
index 7ba77b5..26a4598 100644
--- a/main.js
+++ b/main.js
@@ -1297,23 +1297,23 @@ function start() {
     var allowedLocations2 = document.getElementById("allowed-locations-2");
     const updateAllowedLocations1 = () => {
         allowedLocations2.value = allowedLocations1.value;
-        updateSelection("ini-location", null, rooms[allowedLocations1.value]);
-        updateSelection("sav-location", null, rooms[allowedLocations1.value]);
+        updateSelection("ini-location", undefined, rooms[allowedLocations1.value]);
+        updateSelection("sav-location", undefined, rooms[allowedLocations1.value]);
     };
     const updateAllowedLocations2 = () => {
         allowedLocations1.value = allowedLocations2.value;
-        updateSelection("ini-location", null, rooms[allowedLocations1.value]);
-        updateSelection("sav-location", null, rooms[allowedLocations1.value]);
+        updateSelection("ini-location", undefined, rooms[allowedLocations1.value]);
+        updateSelection("sav-location", undefined, rooms[allowedLocations1.value]);
     };
     allowedLocations1.addEventListener("change", updateAllowedLocations1);
     allowedLocations2.addEventListener("change", updateAllowedLocations2);
     document.getElementById("allow-non-equipables").addEventListener("change", function() {
         if (document.getElementById("allow-non-equipables").checked) {
-            updateSelection("sav-weapon", null, items);
-            updateSelection("sav-armor",  null, items);
+            updateSelection("sav-weapon", undefined, items);
+            updateSelection("sav-armor",  undefined, items);
         } else {
-            updateSelection("sav-weapon", null, weapons);
-            updateSelection("sav-armor",  null, armors);
+            updateSelection("sav-weapon", undefined, weapons);
+            updateSelection("sav-armor",  undefined, armors);
         }
     });
     document.getElementById("sav-havecell").addEventListener("change", function() {
```

**Comment by vinceh121** [comment]
Indeed I hadn't noticed this bug. I've applied your diff.

**Review by KockaAdmiralac — APPROVED** [review]
Thanks!

**Pull request merged**
